### PR TITLE
Constuct GeoArray from array plus coordinate vectors

### PR DESCRIPTION
**Pull request by mauro3**
```julia
    x,y = range(4, stop=8.0, length=10), range(0,stop=1,length=9)
    ga3 = GeoArray(rand(10,9,8), x, y)
```

Note this is based on top of #27.

### CODE REVIEW

**Comment by evetion** [comment]
Specifying the correct step/length seems like a repeated action, as it is known (as you also check in code). I was thinking something along the lines of:

`bbox!(ga::GeoArray, bbox=(minx=4, min=0, maxx=8, maxy=1))`

Would that also fit your use case?

**Comment by mauro3** [comment]
I usually start with x and y and then go from there.  But the bbox is fine too.

**Comment by evetion** [comment]
I've added a `bbox!` method in #38, together with some more improvements.

I've also added an `unitrange_to_affine` method, which is similar to the one you defined in this PR. However its unitranges are corner to corner while you added center-coordinates. Your version seems more logical, but can be very confusing for creation. How can we make the difference clearer? Make a `centercoords!` that takes a x, and y unitrange?

**Comment by mauro3** [comment]
Included in #38

**Pull request closed without merging**
